version: '2.4'
services:
    rsu:
        hostname: rsu
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=15
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    rsu_node:
        hostname: rsu_node
        restart: always
        image: btnode:latest
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40

    obu10:
        hostname: obu10
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=5
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
            - VANETZA_CAM_PERIODICITY=0
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:
            kernel.msgmax: 65536
            kernel.msgmnb: 65536
    main_entity:
        hostname: msg_sender
        restart: always
        image: sender:latest
        environment:
            - IPFS_DAEMON_IP=192.168.98.40
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
    frontend:
        hostname: display
        depends_on:
            - main_entity
        restart: always
        image: frontend:latest
        ports:
            - "5000:5000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.31
    
    entity:
        hostname: entity
        restart: always
        image: activent:latest
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.100

    obu10_node:
        hostname: node10
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50

    connector_10:
        hostname: cn10
        restart: always
        image: connector:latest
        environment:
            - CONNECTOR_ID=0
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.50
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.80


networks:
    vanetzalan0:
        external: true
