FROM python:3.9-slim-buster

EXPOSE 4001 5001 8080

WORKDIR /app

ENV CONNECTOR_ID=

ENV CONNECTOR_QUEUE= 

ENV OBU_IP= 

ENV IPFS_DAEMON_IP= 

COPY main.py denm.json forest.jpg /app/

COPY requirements.txt /app/

RUN pip install -r requirements.txt 

CMD ["python" , "main.py"]
