FROM python:3.9-slim-buster

WORKDIR /app

COPY webviewer.py markers.json /app/

COPY templates/ /app/templates/

COPY static/ /app/static/

COPY leaflet/ /app/leaflet/

COPY requirements.txt /app/

RUN pip install -r requirements.txt 

CMD ["python", "webviewer.py"]