version: '2.4'
services:
    core_unit:
        hostname: core_unit
        restart: always
        image: core:latest
        environment:
            - IPFS_DAEMON_IP=192.168.98.40
            - PYTHONUNBUFFERED=1
            - DRONE_NUMBER=5
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30
    activity_gen:
        hostname: activity_gen
        restart: always
        image: activent:latest
        depends_on:
            - main_entity
        environment:
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.100
    frontend:
        hostname: display
        depends_on:
            - main_entity
        restart: always
        image: frontend:latest
        ports:
            - "5000:5000"
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.101

    drone10:
        hostname: d10
        restart: always
        image: drone:latest
        depends_on:
            - main_entity
        environment:
            - CONNECTOR_ID=0
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.50
            - OBU_IP=192.168.98.10
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.80
    drone11:
        hostname: d11
        restart: always
        image: drone:latest
        depends_on:
            - main_entity
        environment:
            - CONNECTOR_ID=1
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.51
            - OBU_IP=192.168.98.11
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.81
    drone12:
        hostname: d12
        restart: always
        image: drone:latest
        depends_on:
            - main_entity
        environment:
            - CONNECTOR_ID=2
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.53
            - OBU_IP=192.168.98.13
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.82
    drone13:
        hostname: d13
        restart: always
        image: drone:latest
        depends_on:
            - main_entity
        environment:
            - CONNECTOR_ID=3
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.53
            - OBU_IP=192.168.98.13
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.83
    drone14:
        hostname: d14
        restart: always
        image: drone:latest
        depends_on:
            - main_entity
        environment:
            - CONNECTOR_ID=4
            - CONNECTOR_QUEUE=connector/out
            - IPFS_DAEMON_IP=192.168.98.54
            - OBU_IP=192.168.98.14
            - PYTHONUNBUFFERED=1
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.84


networks:
    vanetzalan0:
        external: true
