FROM ipfs/go-ipfs:v0.5.0

EXPOSE 4001 5001 8080

WORKDIR /usr/local/bin

COPY config /usr/local/bin/

COPY start_ipfs.sh /usr/local/bin/start_ipfs.sh

RUN chmod +x /usr/local/bin/start_ipfs.sh

ENTRYPOINT ["/bin/sh", "start_ipfs.sh"]