version: '2.4'
services:
    
    core_node:
        hostname: core_node
        restart: always
        image: btnode:latest
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40
    d10_node:
        hostname: d10_node
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        environment:
            - API_ADDRESS=/ip4/192.168.98.50/tcp/5001
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50
    d11_node:
        hostname: d11_node
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        environment:
            - API_ADDRESS=/ip4/192.168.98.51/tcp/5001
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.51
    d12_node:
        hostname: d12_node
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        environment:
            - API_ADDRESS=/ip4/192.168.98.52/tcp/5001
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.52
    d13_node:
        hostname: d13_node
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        environment:
            - API_ADDRESS=/ip4/192.168.98.53/tcp/5001
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.53
    d14_node:
        hostname: d14_node
        depends_on:
            - rsu_node
        restart: always
        image: regnode:latest
        environment:
            - API_ADDRESS=/ip4/192.168.98.54/tcp/5001
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.54

networks:
    vanetzalan0:
        external: true
