FROM python:3.9-slim-buster

WORKDIR /app

ENV IPFS_DAEMON_IP=

COPY examples/ /app

COPY appv1.py /app

COPY coords/ /app/coords/

COPY requirements.txt /app/

RUN pip install -r requirements.txt 

CMD [ "python" , "appv1.py" ]