FROM ipfs/go-ipfs:latest

EXPOSE 4001 5001 8080

WORKDIR /usr/local/bin

COPY start_ipfs.sh /usr/local/bin/start_ipfs.sh

RUN chmod +x /usr/local/bin/start_ipfs.sh

ENTRYPOINT ["/bin/sh", "start_ipfs.sh"]